version: "3.7"

services:
  db:
    hostname: mysql-user
    container_name: mysql-user
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=user_db
